
apiVersion: v1
kind: Service
metadata:
  name: curio-server
  namespace: curio
  labels:
    app: curio-server
    service: curio-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: curio-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: curio-server-v1
  namespace: curio
  labels:
    app: curio-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curio-server
      version: v1
  template:
    metadata:
      labels:
        app: curio-server
        version: v1
    spec:
      imagePullSecrets:
      - name: github-container-registry
      containers:
      - name: curio-server
        image: ghcr.io/valentine195/curio-server:{{ .Values.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres_user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres_password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES
        - name: SMITHSONIAN_KEY
          valueFrom:
            secretKeyRef:
              name: curio-api-keys
              key: SMITHSONIAN_KEY