/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UsageFlag = string;

export interface EdanMDM {
  descriptiveNonRepeating: DescriptiveNonRepeating;
  indexedStructured?: IndexedStructured;
  descriptiveOptional?: DescriptiveOptional;
  freetext?: {
    [k: string]: {
      label?: string;
      content?: string;
      [k: string]: unknown;
    }[];
  };
}
export interface DescriptiveNonRepeating {
  title_sort: string;
  title: {
    content: string;
    label: string;
  };
  online_media?: OnlineMediaDRAFT;
  data_source: string;
  guid?: string;
  metadata_usage?: {
    access?: string;
    text?: string;
  };
  record_ID: string;
  record_link?: string;
  unit_code: string;
}
/**
 * Object that stores all media within a record.
 */
export interface OnlineMediaDRAFT {
  mediaCount?: string;
  media?: OnlineMediaElementObjectDRAFT[];
}
export interface OnlineMediaElementObjectDRAFT {
  content: string;
  summary?: string;
  guid?: string;
  voyagerId?: string;
  type: string;
  thumbnail: string;
  idsId?: string;
  caption?: string;
  alt?: string;
  credit?: string;
  rights?: string;
  mime_type?: string;
  usage?: Usage;
  usage_flag?: UsageFlag;
}
export interface Usage {
  access?: string;
  text?: string;
  codes?: string;
}
export interface IndexedStructured {
  sortdate?: string[];
  topic?: string[];
  strat_member?: string[];
  strat_group?: string[];
  coordinates?: string[];
  occupation?: string[];
  object_type?: string[];
  name?: string[];
  usage_flag?: string[];
  online_media_type?: string[];
  language?: string[];
  date?: string[];
  tax_kingdom?: string[];
  "geo_age-era"?: string[];
  strat_formation?: string[];
  tax_phylum?: string[];
  tax_class?: string[];
  tax_family?: string[];
  tax_order?: string[];
  "geo_age-system"?: string[];
  "geo_age-stage"?: string[];
  "geo_age-series"?: string[];
  common_name?: string[];
  "tax_sub-family"?: string[];
  culture?: string[];
  online_media_rights?: string[];
  geoLocation?: unknown[];
  onPhysicalExhibit?: string[];
  exhibition?:
    | {
        building?: string;
        exhibitionTitle?: string;
        externalLink?: string;
        room?: string;
      }
    | {
        building?: string;
        exhibitionTitle?: string;
        externalLink?: string;
        room?: string;
      }[];
  scientific_name?: string[];
  place?: string[];
}
export interface DescriptiveOptional {
  freetext?: string[];
}
