management.endpoints.web.exposure.include: env
management.endpoint.env.show-values: ALWAYS

spring.application.name: curio

spring.liquibase.change-log: db/changelog.yaml

smithsonian.subunits: NMAH,NMAI
smithsonian.download: true